### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by Tanjiraaaaa** [MarkusBordihn/BOs-Fire-Extinguisher#7]
**Is your feature request related to a problem? Please describe.**
It isn't really a problem but the lack of the 1.21 version makes it difficult to update my world

**Describe the solution you'd like**
Please make a version of the mod compatible with Minecraft 1.21

**Describe alternatives you've considered**
I don't see any alteratives

**Additional context**
N/A

**Comment by MarkusBordihn** [comment]
Thanks for the reminder. Since the mod uses Forge Config API, I had to wait for a port to the current version. Fortunately, the port for 1.21 is already available, so I can start porting the mod now.

There are still a few smaller parts left that I need to fix:
![image](https://github.com/user-attachments/assets/b0614406-21b1-49c8-8266-79748be9a906)
